### PR TITLE
Fix current_application_info

### PR DESCRIPTION
**Pull request by mattico**
API Reference: https://discordapp.com/developers/docs/topics/oauth2#get-current-application-information

### CODE REVIEW

**Comment by Mishio595** [comment]
Why is description an Option? Per the docs, description is not nullable or optional.

**Comment by mattico** [comment]
I vaguely remember encountering a null response for that, but we can stick to the docs.

**Comment by Erk-** [comment]
This is also a breaking change so it should be retargeted to `v0.6.x`

**Comment by mattico** [comment]
Done

**Comment by Lakelezz** [comment]
Thank you : )

**Pull request merged**
