### PR TITLE
Make FullEvent fields non exhaustive

### PR DESCRIPTION
**Pull request by jamesbt365**
Right now we can't add fields to events without it being a breaking change, unless I'm missing anything this should let us do that.

### CODE REVIEW

**Comment by cheesycod** [comment]
I personally dislike this change, I would prefer for all FullEvent changes to be breaking so I am informed of new stuff and can add those features to my bot as they're added to serenity

Then again, I suppose it doesnt matter much, given I use the ``unstable`` feature flag anyways...

**Comment by DPlayer234** [comment]
Would this even fix the issue? The same macro is used to generate the `EventHandler` trait's functions, so adding a field would still break users/implementors of `EventHandler`. Not exposing all fields of `FullEvent` in `EventHandler` also doesn't sound good.

**Comment by cheesycod** [comment]
Honestly, if you really wanted this, maybe the fields should just put in a struct instead like ``FullEventMessageData`` and so on, then adding new fields would just add to the struct and not break the functions.

**Comment by jamesbt365** [comment]
Right, i forgot about the functions, I wonder if theres a nice way to do this without throwing everything into a struct.

**Comment by jamesbt365** [comment]
> I personally dislike this change, I would prefer for all FullEvent changes to be breaking so I am informed of new stuff and can add those features to my bot as they're added to serenity
> 
> Then again, I suppose it doesnt matter much, given I use the `unstable` feature flag anyways...

And I would prefer not having to do a breaking version bump to add fields to events!

**Comment by jamesbt365** [comment]
The only way I can see this working is if we drop the function method and make users match the fullevent themselves, not sure if this is a warranted change.

**Pull request closed without merging**
