### PR TITLE
Deserializing from `str` in `fire` is faster

### PR DESCRIPTION
**Pull request by noituri**

### CODE REVIEW

**Comment by noituri** [comment]
https://github.com/serenity-rs/serenity/issues/785

**Comment by Erk-** [comment]
Would it be faster again to do it the following way?
```rust
response.json::<T>().map_err(From::from)
```

**Comment by noituri** [comment]
So from what I've seen `.json` uses `from_slice` so in theory it should work just fine. I haven't done any tests yet but I think it will do the job.

**Comment by noituri** [comment]
I did some tests and it works perfectly.

**Review by Erk- — APPROVED** [review]

**Review by evieluvsrainbows — APPROVED** [review]

**Pull request merged**
