### PR TITLE
Replace "discordapp.com" with "discord.com"

### PR DESCRIPTION
**Pull request by s0lst1ce**
Recently discord moved from `discordapp.com` to simply `discord.com`. This PR changes the URL in the README.md accordingly.
I have looked for occurences of the URL outside of the README but couldn't find any. If I missed something I can add them to this PR.

### CODE REVIEW

**Comment by vicky5124** [comment]
Feel free  to move this to the "next" branch.
"current" will no longer obtain any updates.

**Comment by s0lst1ce** [comment]
Very well, seems like I misunderstood the contribution guidelines.

**Comment by Lakelezz** [comment]
We should look into replacing all references to the old Discord domain, as that would qualify to port to 0.7 and 0.8!
@acdenisSK do you think it's worth extending this pull request to more than just this small change?

You will be able to find quite a lot "discordapp.com"-references in the codebase, a small search in VSCode gave me many results.

**Comment by arqunis** [comment]
@Lakelezz I was just about to post my answer that we might as well replace *all* instances of "discordapp.com" with "discord.com" in the repository with this PR, so yes.

**Comment by vicky5124** [comment]
with the exception of cdn.discordapp.com

**Comment by s0lst1ce** [comment]
Ok I will do this then. I've only done this through GH intterface, seems like its search function isn't very good.

**Comment by s0lst1ce** [comment]
Just updated the urls in source files (except for `cdn.discordapp.com`).

**Comment by arqunis** [comment]
I've changed the target branch back to `current` as to merge it neatly from Github's interface. The replacement change can easily be bidirectionally ported to 0.7 and 0.9.
  
@nitsuga5124 the `current` branch, or the 0.8 series, *will* be receiving updates. It just won't be getting new features, only bugfixes.

**Comment by arqunis** [comment]
I have taken the liberty of merging this manually, with the `parse_invite` utility function fixed.
https://github.com/serenity-rs/serenity/commit/f98e61eed83f7c51c26c41ea84f0712888cc7dcd

**Pull request closed without merging**
