### PR TITLE
WIP: Format the code with cargo fmt

### PR DESCRIPTION
**Pull request by MOZGIII**
```rust
$ cargo -V
cargo 1.38.0 (23ef9a4ef 2019-08-20)

$ cargo fmt --version
rustfmt 1.4.4-stable (0462008 2019-08-06)

$ cargo +nightly fmt --version
rustfmt 1.4.9-nightly (33e3667 2019-10-07)
```

### CODE REVIEW

**Comment by Flat** [comment]
I believe you may be targeting the wrong branch or need to fix your git history.

**Comment by MOZGIII** [comment]
Pardon me, I submitted it to the `current` branch

**Comment by MOZGIII** [comment]
Had to fix broken macro as it's not going to work with fmt

**Comment by MOZGIII** [comment]
Please put this on hold!
https://github.com/rust-lang/rustfmt/issues/3866

**Comment by MOZGIII** [comment]
Nightly has less issues, reapply the fmt again with `cargo +nightly fmt`

**Comment by arqunis** [comment]
No progress has been since October; I'm closing this. However this will be revisited once Serenity becomes asynchronously capable of performing I/O via `async`/`await`.

**Pull request closed without merging**
