### PR TITLE
Underline command name and "Commands" in plain help

### PR DESCRIPTION
**Pull request by hyarsan**

### CODE REVIEW

**Comment by hyarsan** [comment]
Before:
before
After:
after

**Comment by Lakelezz** [comment]
@Roughsketch and @Mishio595, since I know you both use plain-help, what do you think of this change?

I am torn apart on accepting this for current-branch and v0.6.x, too.

**Comment by Mishio595** [comment]
I think it helps create a contrast between the command name and the help information. Looks good.

**Comment by acdenisSK** [comment]
Cherry-picked.

**Pull request closed without merging**
