### PR TITLE
Make absolute ratelimits a runtime config instead of feature

### PR DESCRIPTION
**Pull request by kangalio**
Screenshot_20221026_011244

One feature down

### CODE REVIEW

**Review by arqunis — APPROVED** [review]

**Review by arqunis — CHANGES_REQUESTED** [review]
That was a premature approval (not that the changes are bad). Could you also remove the `absolute_ratelimits` feature, or add a warning to [build.rs](https://github.com/serenity-rs/serenity/blob/next/build.rs) that it's deprecated and you must now configure `Http` at runtime?

**Comment by kangalio** [comment]
Done
Screenshot_20221027_184355

**Comment by kangalio** [comment]
Good catch, by the way, thanks :)

**Review by arqunis — APPROVED** [review]

**Comment by kangalio** [comment]
The CI failure is unrelated to this PR. It happens on upstream `next` too and is due to a bad interaction of #2254 and #2256

**Pull request merged**
