### PR TITLE
Add `invite_url_with_oauth2_scopes()` to `CurrentUser` and `CreateBotAuthParameters` builder.

### PR DESCRIPTION
**Pull request by vicky5124**
Made a way to generate an invite url that allows for Slash Commands oauth2 scopes, as the current one is limited to just `bot`; and while i was at it, i added the rest of the allowed oauth2 scopes.

	modified:   src/model/mod.rs
	new file:   src/model/oauth2.rs
	modified:   src/model/prelude.rs
	modified:   src/model/user.rs

### CODE REVIEW

**Comment by Zaitara** [comment]
Maybe that you should also include support to others query params https://discord.com/developers/docs/topics/oauth2#bot-authorization-flow-bot-auth-parameters ?

**Comment by vicky5124** [comment]
> Maybe that you should also include support to others query params https://discord.com/developers/docs/topics/oauth2#bot-authorization-flow-bot-auth-parameters ?

I will look into making a builder for this.

**Comment by vicky5124** [comment]
Fixed a typo and tested with
```rust
        let user = _ctx.cache.current_user().await;

        let scopes = vec![Oauth2Scope::Bot, Oauth2Scope::ApplicationsCommands];
        let permissions = Permissions::READ_MESSAGES | Permissions::SEND_MESSAGES | Permissions::EMBED_LINKS;
        
        // assuming the user has been bound
        let url = match user.invite_url_with_oauth2_scopes(&_ctx, permissions, &scopes).await {
            Ok(v) => v,
            Err(why) => {
                println!("Error getting invite url: {:?}", why);
        
                return;
            },
        };

        println!("{}", url);
```
and it's ready to be merged.
The other builder methods were also tested with success.

**Comment by arqunis** [comment]
This has been manually squash-merged onto `current` as https://github.com/serenity-rs/serenity/commit/50cd28595b007c3501771ae32b6c6f25c08cb834 (with some adjustments from myself to the `CreateBotAuthParameters` builder and the change of name from `Oauth2Scope` to `OAuth2Scope`).

**Pull request closed without merging**
