### PR TITLE
Add a few missing methods for (Partial)Guild

### PR DESCRIPTION
**Pull request by NotNorom**

### CODE REVIEW

**Comment by Zaitara** [comment]
Could you also include other missing methods, here is a (non-exhaustive?) list of missing methods that I found:

- missing `await-*` in `Guild`
- missing `audit_logs`, `channel_id_from_name`, `edit_role`, `edit_role_position`, `greater_member_hierarchy`, `reorder_channels`, `start_prune` in `PartialGuild`

**Comment by NotNorom** [comment]
**PartialGuild**
- [x] audit_logs
- [x] banner_url
- [x] channel_id_from_name
- [x] edit_role
- [x] edit_role_position
- [x] greater_member_hierarchy
- [ ] member_named
- [x] member_permissions
- [ ] members_containing
- [ ] members_nick_containing
- [ ] members_starting_with
- [ ] members_with_status
- [x] reorder_channels
- [x] start_prune

**Guild**
- [x] await-*

**Comment by NotNorom** [comment]
I am done for now, adding the other functions is a bit too much for me :sweat_smile:

**Comment by Zaitara** [comment]
I understand, would you like to give me write permissions on your branch or would you prefer that I make a new PR?

**Comment by NotNorom** [comment]
Write permissions are fine!

**Comment by Zaitara** [comment]
It should be good now, others methods relating to members cannot be added, as a partial guild doesn't contain it.

**Review by Zaitara — APPROVED** [review]

**Comment by NotNorom** [comment]
I see. That was exactly what I was struggling with. Was confused as to how to get the members. Glad that got resolved :D

**Review by arqunis — APPROVED** [review]

**Pull request merged**
