### PR TITLE
Soundboard

### PR DESCRIPTION
**Pull request by cheesycod**
Implements the soundboard. Might be mangled with my PR on `delete_message_seconds`

### CODE REVIEW

**Review by mkrasnitski — COMMENTED** [review]
For the builders, any `Option` fields should be marked `#[serde(skip_serializing_if = "Option::is_none")]`. Also `audit_log_reason` should be marked `#[serde(skip)]`.

**Comment by cheesycod** [comment]
> For the builders, any `Option` fields should be marked `#[serde(skip_serializing_if = "Option::is_none")]`. Also `audit_log_reason` should be marked `#[serde(skip)]`.

Fixed

**Comment by GnomedDev** [comment]
1. Why is this targeting next? 
2. Yes, you have included part of #3044, please rebase it away.

**Comment by cheesycod** [comment]
> 1. Why is this targeting next?
> 2. Yes, you have included part of [Replace bans delete_message_days with delete_message_seconds #3044](https://github.com/serenity-rs/serenity/pull/3044), please rebase it away.

The reason it targets next is because I really don’t want to touch serenity current which I basically have never touched in the past year or so. Also, all of my discord bots use next so there’s no point in me touching current

as for 2, yeah, will do

**Comment by GnomedDev** [comment]
I am not going to merge this non-breaking change that doesn't rely on changes made to next into next. New discord features go to current, so they can be released as a minor version.

**Comment by cheesycod** [comment]
With james's suggestion on discord about making a test bot, will open a new PR against current for this

**Pull request closed without merging**
