### PR TITLE
Change message builder to use &mut self instead of self

### PR DESCRIPTION
**Pull request by PvdBerg1998**
This way the builder can be used where taking ownership is impractical.
Solves #313 .

### CODE REVIEW

**Comment by PvdBerg1998** [comment]
Note this requires a clone upon building. Maybe there should be a consuming alternative build method to prevent unnecessary clones? Or people could just access builder.0 if they want to optimize their code.

**Comment by zeyla** [comment]
Why change `MessageBuilder::build` to take `&self` instead of `self`?

I can't think of too many use cases where it's better for it to clone, the user should have to explicitly clone if they want that.

**Comment by zeyla** [comment]
Due to some branch rebasing your PR is mostly unmergeable now, I'll clean it up and commit under your name.

**Comment by zeyla** [comment]
Committed as https://github.com/serenity-rs/serenity/commit/67155c71af37c6e4056b153ab63a11424cf78334, thanks.

**Pull request closed without merging**
