### PR TITLE
Add role icons

### PR DESCRIPTION
**Pull request by Rstar284**

### CODE REVIEW

**Comment by Rstar284** [comment]
ignore the last 3 commits, git is being bad.

**Comment by Rstar284** [comment]
Closes #1564

**Review by drklee3 — COMMENTED** [review]
Seems to work when just logging some roles with icons, as shown -- Should also be a good idea to add role icons to the edit role builder.

```rust
        Role {
            ...
            icon: None,
            unicode_emoji: Some(
                "🍣",
            ),
```

```rust
        Role {
            ...
            icon: Some(
                "3bdf3b182270daf9740bbb26d11313c4",
            ),
            unicode_emoji: None,
```

Note about the first 3 commits, you can avoid those by using feature branches instead of your `next` branch and reusing it. Usually I don't touch the target branches in my forks and only use them to base new branches off of. After the feature branch is merged, feature branch is deleted, and upstream target is fetched/pulled to update it to the latest version (then repeat as needed).

**Comment by Rstar284** [comment]
Hmm i dont know how i would add them to the builder. Its confusing tbh

**Pull request closed without merging**
