### PR TITLE
updating some dependencies

### PR DESCRIPTION
**Pull request by DRuppFv**
There are more dependencies not updated, as bitflags, serde_json, chrono and probably some others, but i just updated the really outdated or that had performance updates ones

### CODE REVIEW

**Comment by GnomedDev** [comment]
The only actual update here is simd-json, the others are semver compatible so will automatically be updated when selected for Cargo.lock

**Comment by DRuppFv** [comment]
> The only actual update here is simd-json, the others are semver compatible so will automatically be updated when selected for Cargo.lock

Oh. I didn't know that. It had performance updates, then the PR is still valid, i think?

**Comment by kangalio** [comment]
The tracing and reqwest updates are not helpful because it forces needless dependency updates on people who are still running older (but semver-compatible) dependency versions

**Comment by kangalio** [comment]
Actually, isn't this a breaking change? We publically expose simd_json types, for example in the `serenity::json` module

I believe the PR should be retargetted at next

**Comment by DRuppFv** [comment]
> Actually, isn't this a breaking change? We publically expose simd_json types, for example in the `serenity::json` module
> 
> I believe the PR should be retargetted at next

What do you mean with "retargetted at next"?

**Comment by GnomedDev** [comment]
This should be bumped to 0.6, now that is out.

**Comment by kangalio** [comment]
I think we can close this PR, there hasn't been activity on bumping the simd-json to the new latest version so the PR is outdated

**Pull request closed without merging**
