### PR TITLE
Add `edit_original_message()` for `MessageComponentInteraction`

### PR DESCRIPTION
**Pull request by B-2U**
in the discord api [Interaction Callback Type](https://discord.com/developers/docs/interactions/receiving-and-responding#interaction-response-object-interaction-callback-type)
with value`7` we can update the message the components belong to as a interaction response, but currently under the [MessageComponentInteraction](https://docs.rs/serenity/latest/serenity/model/prelude/prelude/interaction/message_component/struct.MessageComponentInteraction.html#) there's only methods related to defer, reponse and follow-up

So i tried to add it myself, basically the same but specify the `.kind(InteractionResponseType::UpdateMessage)` 
it does work but I'm not sure should it using the same `CreateInteractionResponse` struct, 
although it's editing a message but for discord server it should be the same.

thanks for reading

### CODE REVIEW

**Comment by B-2U** [comment]
I'm not sure if I need to deal with these CI errors?

**Review by arqunis — APPROVED** [review]
The CI failures must be due to the old version of the toolchain. I built it locally, which worked fine.

**Comment by mkrasnitski** [comment]
Just now taking a close look at this as we're approaching release. I'm not sure I understand why this isn't covered by `create_interaction_response`. Couldn't you just call `.kind(InteractionResponseType::UpdateMessage)` within the closure that you pass in as argument?

**Comment by B-2U** [comment]
> Just now taking a close look at this as we're approaching release. I'm not sure I understand why this isn't covered by `create_interaction_response`. Couldn't you just call `.kind(InteractionResponseType::UpdateMessage)` within the closure that you pass in as argument?

You are right, it's much better to do so, I was new to rust at the moment so that happened...

**Comment by mkrasnitski** [comment]
That's ok. I submitted a PR which simplifies the implementation. However, it's likely that on the `next` branch the function will have to be removed, since in #2228, `CreateInteractionResponse` was turned into an enum with variants representing each response type. Therefore, since you can't mutate one enum variant into another, it would be impossible to take an arbitrary `CreateInteractionResponse` and make it of kind `UpdateMessage`.

**Pull request merged**
