### PR TITLE
Add guild commands into ApplicationCommand

### PR DESCRIPTION
**Pull request by SparkyPotato**
This allows guild-specific commands to be created, edited, and destroyed the same way global commands are.

### CODE REVIEW

**Comment by Zaitara** [comment]
This is already supported, see https://serenity-rs.github.io/serenity/current/serenity/model/id/struct.GuildId.html#method.create_application_command

**Comment by SparkyPotato** [comment]
That seems rather counterintuitive, with global commands being separated from guild commands and in a separate module. 

The global command docs don't even link to the guild ones.

On another note, the interactions example should include creating commands, not just responding to interactions.

**Comment by Zaitara** [comment]
The example does include it, see https://github.com/serenity-rs/serenity/blob/695bbef18e06696b9b9d1f46225099e94001b6c8/examples/e14_slash_commands/src/main.rs#L74-L132
I understand but it is the same things for others structures ; a guild channels will be linked to a `GuildId`

**Comment by SparkyPotato** [comment]
Oops, that was added after I last looked at the example. 

Also, the command creation only has to be done once, and not on every bot startup, which should probably be noted there as well.

The `create_global_application_command` docs should also link to the `GuildId` docs.

**Comment by sbrocket** [comment]
I admit that this confused me initially too. I wouldn't add any new methods, and the example is probably enough, but it wouldn't hurt to add a pointer to the GuildId methods in ApplicationCommand's docs too.

Things like "command creation only has to be done once" might be useful too, though it doesn't seem like Serenity's docs in general aim to replace or include all of the nitty gritty detail of Discord's own API documentation

**Comment by teotwaki** [comment]
@SparkyPotato Can this be closed then?

**Pull request closed without merging**
