### PR TITLE
system flags in audit log changes

### PR DESCRIPTION
**Pull request by bend-n**
fixes bug where audit log entries of welcome messages being disabled etc would deserialize as `Unknown`

### CODE REVIEW

**Comment by GnomedDev** [comment]
What's the point of the macro? All I can see it being used for is generating the `name` method which isn't used in this PR and isn't documented in the PR description.

**Comment by bend-n** [comment]
The point is the `name` method which i put, as originally I didnt see that there was already a `SystemFlags` so i modelled it after `Permissions`, so as to make them have more similar apis.

I can remove it if that would be required

**Comment by GnomedDev** [comment]
Please do remove the changes that are not explicitly related to fixing the bug, I see this as an unnecessary complexity.

**Comment by bend-n** [comment]
image
is this normal

**Comment by GnomedDev** [comment]
I think you ran into the emoji in branches bug, that causes github's infra to fall apart if you have an emoji in a branch name. Reopen the PR with a different branch name lol

**Pull request closed without merging**
