### PR TITLE
`GuildChannel#is_text_based` returns `true` for thread channel

### PR DESCRIPTION
**Pull request by m1sk9**
Make `GuildChannel#is_text_based` return `true` for public and private threads.

ref: https://canary.discord.com/channels/381880193251409931/673965002805477386/1305494065613111366 (Serenity Discord)

### CODE REVIEW

**Comment by m1sk9** [comment]
Forgot `cargo fmt`. I have made a correction and need CI approval again.

**Comment by GnomedDev** [comment]
Can a comment be added to the end of `ChannelType` along the lines of "Make sure to update `GuildChannel::is_text_based`" to make sure this stays up to date in future?

**Comment by m1sk9** [comment]
> Can a comment be added to the end of `ChannelType` along the lines of "Make sure to update `GuildChannel::is_text_based`" to make sure this stays up to date in future?

Added https://github.com/serenity-rs/serenity/pull/3025/commits/238c32389b2c6635da964dcdfa29e537b326e1af

**Comment by jamesbt365** [comment]
I'm not sure she meant a doc comment, this is something that only really needs to be updated when the developer changes it, it doesn't need to be visible to the user.

**Comment by m1sk9** [comment]
Okay, you're right. Fixed with an https://github.com/serenity-rs/serenity/pull/3025/commits/abb4d08eae639c1d417365600e5deee4b36ac755.

**Review by GnomedDev — APPROVED** [review]

**Pull request merged**
