### PR TITLE
Add missing audit log events

### PR DESCRIPTION
**Pull request by crivasr**
There are some events that are missing from the audit log

### CODE REVIEW

**Comment by mkrasnitski** [comment]
Could you retarget this at the `next` branch? The `current` branch is currently in code freeze in preparation for the release of serenity 0.12.

**Comment by mkrasnitski** [comment]
You may need to rebase your work, as `next` has diverged quite a bit from `current`. The file you want to look at is now `src/model/guild/audit_log/mod.rs`.

**Comment by crivasr** [comment]
Yeah and the two automoderation types that were missing are already in that branch

**Comment by mkrasnitski** [comment]
> Yeah and the two automoderation types that were missing are already in that branch

Not the monetization-related ones.

**Comment by crivasr** [comment]
I'm struggling a bit with the rebase, never done one. So I'm just gonna create a new PR

**Pull request closed without merging**
