### PR TITLE
Fix scheduled event

### PR DESCRIPTION
**Pull request by marcantoinem**
This PR fix a regression on scheduled event with #2232 . (See bug #2306) It just replace `ScheduledEvent` -> `GuildScheduledEvent` where it was before #2232 .

### CODE REVIEW

**Comment by mkrasnitski** [comment]
Hi, thanks for the PR! Note that we use some nightly-only `rustfmt` options. You should therefore run `cargo +nightly fmt` to fix some of the formatting here.

**Comment by marcantoinem** [comment]
Thanks for the info, I've fixed that.

**Review by arqunis — APPROVED** [review]

**Comment by kangalio** [comment]
Why did you rename ScheduledEvent back to GuildScheduledEvent?

**Comment by marcantoinem** [comment]
The name of these structs seem to be relied to the call in the api for the event handler. (https://discord.com/developers/docs/resources/guild-scheduled-event) With the name `ScheduledEvent`, it no longer register any events for `GuildScheduledEvent`. (see the bug #2306) I'm not exactly sure how the name of the struct is directly connect to the call in the api, but reverting back to `GuildScheduledEvent` fixed it.

**Comment by kangalio** [comment]
Ohh I see. Yes the enum variant name is used for JSON serialization which I didn't think about when making #2232. It could be fixed with a `#[serde(rename = "...")]` though not sure if I care enough about the more concise name to make yet another PR

**Pull request merged**
