### PR TITLE
[routing] Fix various incorrect routes.

### PR DESCRIPTION
**Pull request by Lymia**

### CODE REVIEW

**Comment by zeyla** [comment]
Thanks

**Comment by vityafx** [comment]
I am curious, why these changes were needed? Did it work earlier? Did discord api change? There is no description at all.

**Comment by Mishio595** [comment]
@vityafx See [this commit that abstracted routing methods](https://github.com/serenity-rs/serenity/commit/bbbf63868a8ef3c0f21c1896f7afb96f4d8fbcc1)

**Comment by vityafx** [comment]
@Mishio595 Thanks. I think it is still good to write a description for the changes, both in commit and in pull request.

**Pull request merged**
