### PR TITLE
Make `CreateApplicationCommandPermissions` public

### PR DESCRIPTION
**Pull request by ghost**
You currently can't use the `GuildId::create_application_command_permission` builder because `CreateApplicationCommandPermissionsData::add_permission` requires you to supply it with a `CreateApplicationCommandPermissionData`, but `CreateApplicationCommandPermissionData` is not exported in `mod.rs`.

### CODE REVIEW

**Comment by Zaitara** [comment]
> You currently can't use the `GuildId::create_application_command_permission` builder because `CreateApplicationCommandPermissionsData::add_permission` requires you to supply it with a `CreateApplicationCommandPermissionData`, but `CreateApplicationCommandPermissionData` is not exported in `mod.rs`.

Note that you can still use `GuildId::create_application_command_` with `create_permission`, only `add_permission` is affected

**Review by Zaitara — APPROVED** [review]
Please fix the CI errors

**Comment by ghost** [comment]
I've fixed the lint error, but I'm not sure how to fix the docs error. It references `Self::channel` in `src/cache/mod.rs`, which is far from where I've edited files. Any ideas on why this could've happened?

**Comment by Zaitara** [comment]
No, there are others errors which I can't can screen right now - See the CI tests result

**Comment by ghost** [comment]
i've discovered the scroll wheel and fixed the ci, sorry about that

**Review by Zaitara — APPROVED** [review]
Thank you!

**Review by arqunis — APPROVED** [review]

**Pull request merged**
