### PR TITLE
Sync model structs/enums

### LINKED ISSUE #2056: Better synchronize model types with Discord API documentation
It's a chore to use model types because

- they're missing some fields
- they have some redundant Option\<T> fields that users _think_ they can use but they're just always None
- other fields have lacking docs (e.g. Option\<T> fields not mentioning they're only sometimes populated, leaving users confused)

All of this could be solved by better integrating the official Discord API docs into serenity.

I think all model types should include a link to the official object structure docs (like #1965).

Ideally, we would also have a tool that parses serenity source code using syn and scrapes Discord API docs, to make sure serenity's model types have correct fields and include Discord's official field documentation

### PR DESCRIPTION
**Pull request by kangalio**
I made a Python script that parses serenity's model structs (via rustdoc JSON), extracts the Discord docs link contained in most of them, parses the Discord docs, and prints out mismatches. Going through it is a long process. It's 8 hours since I started writing the script and like 5 hours since I started working through its output (37 commits now!). It's 4:30 AM now and imma take a break lul.

The commits are atomic and should be easy to review.

Closes #2056 

Todo:
- Some of the Discord docs link are outdated (the script has link rewriting and retry logic built in to workaround this, but the links should be updated within serenity itself
- Test this PR

<details>
<summary>Python script used (I'm building up the large list of false positives as I go)</summary>

```py
from typing import *
import json, re, bs4, requests, marko, marko.ext.gfm as gfm, joblib, glob

memory = joblib.Memory("cachedir", verbose=0)
@memory.cache
def http_get(url: str) -> str:
    return requests.get(url).text

def convert_discord_to_github_link(url: str) -> str:
    query = "developers/docs/"
    path = url[url.find(query) + len(query):]
    filename = path[path.rfind("/")+1:]
    new_filename = "_".join(word[0].upper() + word[1:] for word in filename.split("-"))
    path = path.replace(filename, new_filename)
    return f"https://raw.githubusercontent.com/discord/discord-api-docs/main/docs/{path}.md"

def find_markdown_after(url: str, words: [str]) -> Optional[str]:
    markdown = http_get(convert_discord_to_github_link(url))
    for i in range(len(words) - 1):
        query = "# " + " ".join(words[i:]) + "\n"
        pos = markdown.find(query)
        if pos != -1:
            return markdown[markdown.find(query) + len(query):]
    return None

def red(text: str) -> str:
    ANSI_RED_BOLD = "\033[31;1m"
    ANSI_RESET = "\033[0m"
    return ANSI_RED_BOLD + text + ANSI_RESET

renames = {}
for path in glob.iglob("../src/model/**/*.rs", recursive = True):
    regex = """#\[serde\(rename = "([a-z_]+)"\)\]\n    pub ([a-z_]+):"""
    renames_in_this_file = {match.group(2): match.group(1) for match in re.finditer(regex, open(path).read())}
    renames[path[path.find("src/model"):]] = renames_in_this_file
def rename_field(file_path: str, field: str) -> str:
    if file_path in renames:
        if field in renames[file_path]:
            return renames[file_path][field]
    return field

def check_struct(src_link: str, file_path: str, struct_name: str, fields: [str], discord_url: str):
    url, jump_to = discord_url.split("#")

    words = [word[0].upper() + word[1:] for word in jump_to.split("-")]
    markdown = find_markdown_after(url, words)
    outdated_docs_link = False
    if markdown is None:
        if url.endswith("/gateway"):
            url = url.replace("/gateway", "/gateway-events")
            discord_url = url + "#" + jump_to # used later
            markdown = find_markdown_after(url, words)
        if markdown is None:
            raise Exception(f"cannot find {jump_to} in {discord_url}")
        else:
            outdated_docs_link = True

    markdown = gfm.gfm.parse(markdown)
    table = next(child for child in markdown.children if isinstance(child, gfm.elements.Table))

    def marko_to_str(elem) -> str:
        if isinstance(elem, marko.inline.Emphasis):
            return f"_{marko_to_str(elem.children[0])}_"
        elif isinstance(elem, marko.inline.StrongEmphasis):
            return f"**{marko_to_str(elem.children[0])}**"

        try:
            children = getattr(elem, "children")
        except Exception:
            return str(elem)
        return "".join(marko_to_str(child) for child in children)

    table_cols = [marko_to_str(cell) for cell in table.children[0].children]
    rows = [{col: marko_to_str(cell) for col, cell in zip(table_cols, row.children)} for row in table.children[1:]]
    
    for row in rows:
        row["Field_cleaned"] = re.match(r"[A-Za-z_]*", row["Field"]).group(0)

    discord_fields = set(row["Field_cleaned"] for row in rows)
    serenity_fields = set(rename_field(file_path, field) for field in fields)
    
    missing_fields = list(discord_fields - serenity_fields)
    extra_fields = list(serenity_fields - discord_fields)

    if len(missing_fields) == 0 and len(extra_fields) == 0: return

    print(f"[{struct_name}]")
    print(f"Source link: {src_link}")
    print(f"Serenity link: https://serenity-rs.github.io/serenity/next/serenity/?search={struct_name}")
    print(f"Discord link: {discord_url}")
    if outdated_docs_link:
        print(red(f"Outdated Discord docs link on {struct_name}!"))
    if len(missing_fields) > 0:
        print(red(f"Missing fields: {missing_fields}"))
        for field in missing_fields:
            try:
                description = next(row["Description"] for row in rows if row["Field_cleaned"] == field)
                description = description[0].upper() + description[1:] + "."
            except Exception as e:
                print(json.dumps(rows, indent=4))
                print(e)
                exit(1)
                description = f"FAILED: {e}"
            print(f"    /// {description}")
            print(f"    pub {field}: AAA,")
    if len(extra_fields) > 0:
        print(red(f"Extra fields: {extra_fields}"))
    print()

# serenity = json.load(open("serenity-rustdoc-excerpt.json"))
serenity = json.load(open("../target/doc/serenity.json"))

# check_struct("TriggerMetadata", [], "https://discord.com/developers/docs/resources/auto-moderation#auto-moderation-rule-object-trigger-metadata")
# exit(0)

for obj in sorted(serenity["index"].values(), key = lambda obj: obj["id"]):
    doc = obj.get("docs")
    if doc is None: continue
    
    if obj["kind"] != "struct": continue
    if not obj["span"]["filename"].startswith("src/model"): continue

    inner = obj["inner"]["kind"]
    if "plain" not in inner: continue
    fields = [serenity["index"][field]["name"] for field in inner["plain"]["fields"]]

    discord_url = re.search(r"\[Discord docs\]\((https.*)\)", doc)
    if discord_url is None: continue
    discord_url = discord_url.group(1)

    struct_name = obj["name"]
    file_path = obj["span"]["filename"]
    src_link = f'{obj["span"]["filename"]}:{obj["span"]["begin"][0]}:{obj["span"]["begin"][1]}'

    bitflag_structs = ["InteractionResponseFlags", "ApplicationFlags", "MessageFlags", "ChannelFlags", "ThreadMemberFlags", "SystemChannelFlags", "ActivityFlags", "GatewayIntents", "Permissions"]
    if struct_name in bitflag_structs:
        print(f"Skipping {struct_name} because this script doesn't support bitflags yet")
        continue
    if struct_name in ["Gateway", "InviteChannel"]:
        print(f"Skipping {struct_name} because the script can't read example response codeblocks")
        continue
    if struct_name in ["ReactionRemoveEmojiEvent", "GuildScheduledEventUpdateEvent", "ThreadCreateEvent", "CommandPermissionsUpdateEvent", "ChannelCreateEvent", "ThreadMemberUpdateEvent", "AutoModRuleCreateEvent", "AutoModRuleUpdateEvent", "AutoModRuleDeleteEvent", "AutoModActionExecutionEvent", "ChannelDeleteEvent", "ChannelUpdateEvent", "GuildAuditLogEntryCreateEvent", "GuildCreateEvent", "GuildDeleteEvent", "GuildMemberAddEvent", "GuildUpdateEvent", "MessageCreateEvent", "MessageUpdateEvent", "PresenceUpdateEvent", "ReactionAddEvent", "ReactionRemoveEvent", "ReactionRemoveAllEvent"]:
        print(f"Skipping {struct_name} because #[serde(transparent)] and the Discord docs only contain a link which this script can't read")
        continue
    if struct_name in ["Role"]:
        print(f"Skipping {struct_name} as FP due to serenity's virtual guild_id field")
        continue
    if struct_name in ["ThreadMember", "Message"]:
        print(f"Skipping {struct_name} as FP due to extra field(s) in some contexts")
        continue
    if struct_name in ["Sticker"]:
        print(f"Skipping {struct_name} as FP because the only missing field is deprecated by Discord")
        continue
    if struct_name in ["PartialGuildChannel", "UnavailableGuild", "PartialChannel"]:
        print(f"Skipping {struct_name} as FP due to not recognizing type subsets")
        continue
    if struct_name in ["PermissionOverwrite"]:
        print(f"Skipping {struct_name} as FP due to not recognizing multiple fields being abstracted by an enum in the kind field")
        continue
    if struct_name in ["GuildChannel"]:
        print(f"Skipping {struct_name} as FP because those fields are about group DMs, which GuildChannel is not about")
        continue
    if struct_name in ["GuildRoleCreateEvent", "GuildRoleUpdateEvent"]:
        print(f"Skipping {struct_name} as FP due to manual (De)Serialize implementation")
        continue
    if struct_name in ["PrivateChannel", "MessageApplication"]:
        print(f"Tentatively skipping {struct_name} as FP because I can't find docs about this type subset anywhere")
        continue


    # check_struct(src_link, file_path, struct_name, fields, discord_url)
    try:
        check_struct(src_link, file_path, struct_name, fields, discord_url)
    except Exception as e:
        print(red(f"Exception: {e}"))
```

</details>

### CODE REVIEW

**Comment by kangalio** [comment]
At this point I went through every model item that has a Discord docs link and:
- is a struct
- has `obj["inner"]["kind"] == "plain"` in the rustdoc representation, not exactly sure what that means, but that seems to be what "normal" structs have

To recap, I did this by having my Python script iterate through all public serenity items, filter according to above, and then output field mismatches between Rust struct and linked Discord docs on a best-effort basis. This process had many false positives, but shouldn't really have any false negatives. So, having worked through the entire output of the script, all structs matching the above description should be up-to-date now.

What's now left to do is going through the remaining model items (basically just enums, as far as I can tell)

After that, the only two remaining venues where we could possibly not be bleeding edge up-to-date are:
- items that don't have a Discord docs link yet
- items that are absent from serenity completely (and are also not references as fields in any already-implemented items)

Those two shall be taken care of in future PRs, this one is already humongous enough.

**Comment by kangalio** [comment]
**Every item in `src/model` that has a Discord docs link has now been checked by me and should be up-to-date.** This PR is ready-to-review

**Comment by GnomedDev** [comment]
Should the script be added to CI? This would prevent fields drifting out of sync.

**Comment by kangalio** [comment]
> Should the script be added to CI? This would prevent fields drifting out of sync.

No, at least not without a thorough rewrite. It's a throwaway piece of code which is absolute spaghetti, has glaring bugs that were quicker to just work around manually, and a way too coarse false positive system.

To prevent fields drifting out of sync, I believe we should instead watch the [Discord changelog](https://discord.com/developers/docs/change-log) from now on, and/or watch merged [discord-api-docs](https://github.com/discord/discord-api-docs) PRs

**Comment by kangalio** [comment]
I went through all items that don't have a Discord docs link after all. Added the link, and checked if the fields are up-to-date. The above 4 commits are the result of that.

Now every model type within src/model should be up-to-date

**Comment by GnomedDev** [comment]
> > Should the script be added to CI? This would prevent fields drifting out of sync.
> 
> No, at least not without a thorough rewrite. It's a throwaway piece of code which is absolute spaghetti, has glaring bugs that were quicker to just work around manually, and a way too coarse false positive system.
> 
> To prevent fields drifting out of sync, I believe we should instead watch the [Discord changelog](https://discord.com/developers/docs/change-log) from now on, and/or watch merged [discord-api-docs](https://github.com/discord/discord-api-docs) 

Isn't watching the Discord changelog and merged PRs what we were doing before, that caused this?

**Comment by kangalio** [comment]
> Isn't watching the Discord changelog and merged PRs what we were doing before, that caused this?

Well at least speaking for myself, I was definitely not watching the Discord change log and merged PRs. I assumed @mkrasnitski didn't either

I was gonna ask acdenisSK if we can get a channel that logs discord-api-docs commits. I'll start watching API updates thoroughly then

**Review by arqunis — APPROVED** [review]

**Comment by kangalio** [comment]
Fixed merge conflicts (and added one new commit that proved useful when testing this PR with poise and rustbot/Ferris)

**Comment by kangalio** [comment]
Windows CI failure unrelated

**Comment by mkrasnitski** [comment]
What breaking changes does this PR contain? I haven't looked closely because of the sheer size, but I wouldn't expect field additions to be considered breaking.

**Comment by kangalio** [comment]
Field/variant additions aren't breaking (the structs/enums that weren't marked non_exhaustive have been broken by #2397 anyways).

But some commits change field types or remove fields. Should I make a list of all those? Your WIP change log is already quite high level so it might be enough to just say that some model types have been removed or changed types?

**Comment by mkrasnitski** [comment]
If it's not too much trouble, and since the commits here seem to be pretty self-contained, just a list of the commits that contain breaking changes would be good to have as a reference. For the changelog, I'd rather be specific about removals and type changes, less so for additions.

**Comment by kangalio** [comment]
Removed fields:
- 59a9fd4fa819699dbafb16d928053cc0e33a144f (`59a9fd4fa819699dbafb16d928053cc0e33a144f`)
- 0ccfa96cc17b1ae16eddb0fa9bb6ffb76aac8209 (`0ccfa96cc17b1ae16eddb0fa9bb6ffb76aac8209`)
- 8187903cdfd07c2a85aa70c50914eee8b5ca8219 (`8187903cdfd07c2a85aa70c50914eee8b5ca8219`)
- 81e457486a341ce1c8927a4b1bd3b7cc12df6977 (`81e457486a341ce1c8927a4b1bd3b7cc12df6977`)
- 12b761a063b623018141e3327e3432aba463b2b8 (`12b761a063b623018141e3327e3432aba463b2b8`)
- e42ef2ea96e633a6ff6a7a1f226d6407621ebd92 (`e42ef2ea96e633a6ff6a7a1f226d6407621ebd92`)
- 9e4112d59db6255c4eb979a7aab53013c4606c43 (`9e4112d59db6255c4eb979a7aab53013c4606c43`)

Changed field types:
- 1ad4d979c343672e00b66d3b154ca5c70a3dfd56 (`1ad4d979c343672e00b66d3b154ca5c70a3dfd56`)
- 4f411649f45b5f262ee079cc0c2733a52935a659 (`4f411649f45b5f262ee079cc0c2733a52935a659`)
- 9f0dd1884c0c79045465db3374138bc01e633452 (`9f0dd1884c0c79045465db3374138bc01e633452`)
- 7f03edd76f506753a190add4b695d10f5a6323af (`7f03edd76f506753a190add4b695d10f5a6323af`)
- 92e8be6c09567f3cb5737a5f71b2f0f390e80c63 (`92e8be6c09567f3cb5737a5f71b2f0f390e80c63`)
- dabdf17fbd4336892755a1e5efb6e2632ca0e735 (`dabdf17fbd4336892755a1e5efb6e2632ca0e735`)
- e42ef2ea96e633a6ff6a7a1f226d6407621ebd92 (`e42ef2ea96e633a6ff6a7a1f226d6407621ebd92`)
- 82b91af84be445f1247f631091afdd0234be5f63 (`82b91af84be445f1247f631091afdd0234be5f63`)
- 74600e5a0a3c155c68c9c6a1a17b6d473e48d157 (`74600e5a0a3c155c68c9c6a1a17b6d473e48d157`)

Changed field names:
- c5e58a88319b5013759282f42585ab4f435304b1 (`c5e58a88319b5013759282f42585ab4f435304b1`)
- dd092eaa874a076e87f101b2000b1995ff1a174d (`dd092eaa874a076e87f101b2000b1995ff1a174d`)
- 92e8be6c09567f3cb5737a5f71b2f0f390e80c63 (`92e8be6c09567f3cb5737a5f71b2f0f390e80c63`)

Removed enum variant:
- 9ca61966be9913eafce93ceab38ed168e53e1b24 (`9ca61966be9913eafce93ceab38ed168e53e1b24`)
- c32c267d2c8cc515ffa4c73922031a9f006d6197 (`c32c267d2c8cc515ffa4c73922031a9f006d6197`)

Changed enum variant type:
- 9ca61966be9913eafce93ceab38ed168e53e1b24 (`9ca61966be9913eafce93ceab38ed168e53e1b24`)

Changed enum variant name:
- c32c267d2c8cc515ffa4c73922031a9f006d6197 (`c32c267d2c8cc515ffa4c73922031a9f006d6197`)
- d7d81772c6e5351382fb351a6661f3df59a03d40 (`d7d81772c6e5351382fb351a6661f3df59a03d40`)

Removed methods:
- 31e6ea788d6b485159c177866e43169cb535b9cb (`31e6ea788d6b485159c177866e43169cb535b9cb`)

**Comment by cheesycod** [comment]
This PR introduces a regression in runtime in like every command for me literally so yeah

**Comment by kangalio** [comment]
@cheesycod Can you share the measurements you made? I'd like to pinpoint the problem

Edit: just read the [Discord messages](https://discord.com/channels/381880193251409931/673965002805477386/1101583259365814323): it's not a performance regression, but many deserializations now error.

**Pull request merged**
