### PR TITLE
Fix deserialization of burst_colours on MessageReaction

### LINKED ISSUE #2892: Invalid Type Error
Iterating over all the messages in a server yields me an invalid type error every time. The error is:
`invalid type: string "#d0334d", expected u32 at line 1 column 123537`
I don't really know what to do in order to help debug this but I assume this is a deserialization error.
Branch: `current`

### PR DESCRIPTION
**Pull request by jamesbt365**
Fixes #2892.

### CODE REVIEW

**Review by GnomedDev — CHANGES_REQUESTED** [review]
I'm not merging this as-is, we cannot duplicate logic like this. There must be a better way to do this.

**Comment by jamesbt365** [comment]
I couldn't think of a nicer way at the time, It would probably involve the creation of another module (so that it doesn't reexport the function in serenity::all, or changing it carefully so it reexports *everything* but this function) alongside somehow handling the difference between the optional and non optional version.

Do you have any suggestions in mind?

**Comment by GnomedDev** [comment]
Can this not go in `/src/model/utils.rs`?

**Comment by jamesbt365** [comment]
I didn't think about moving it there to be fair, <sub>I don't think much</sub>, that only leaves one issue with one being an option and the other not.

**Comment by jamesbt365** [comment]
Would this pass?

```rs
fn discord_colours_opt<'de, D>(deserializer: D) -> Result<Option<Vec<Colour>>, D::Error>
where
    D: Deserializer<'de>,
{
    let vec_str: Option<Vec<CowStr<'_>>> = Deserialize::deserialize(deserializer)?;

    let Some(vec_str) = vec_str else { return Ok(None) };

    if vec_str.is_empty() {
        return Ok(None);
    }

    deserialize_colours::<D>(vec_str).map(Some)
}

fn discord_colours<'de, D>(deserializer: D) -> Result<Vec<Colour>, D::Error>
where
    D: Deserializer<'de>,
{
    let vec_str: Vec<CowStr<'_>> = Deserialize::deserialize(deserializer)?;

    deserialize_colours::<D>(vec_str)
}

fn deserialize_colours<'de, D>(vec_str: Vec<CowStr<'_>>) -> Result<Vec<Colour>, D::Error>
where
    D: Deserializer<'de>,
{
    vec_str
        .into_iter()
        .map(|s| {
            let s = s.0.strip_prefix('#').ok_or_else(|| DeError::custom("Invalid colour data"))?;

            if s.len() != 6 {
                return Err(DeError::custom("Invalid colour data length"));
            }

            u32::from_str_radix(s, 16)
                .map(Colour::new)
                .map_err(|_| DeError::custom("Invalid colour data"))
        })
        .collect()
}
```

**Comment by GnomedDev** [comment]
Sure

**Comment by AlexCzar** [comment]
Do I understand correctly, that 0.12.* won't work with reactions until this is merged?
I'm trying to update my bot to latest version and see following error:
```none
missing field `burst_colours` at line 1 column 816
```
at
```rust
    ctx.http
        .get_message(reaction.channel_id.into(), message_id.into())
        .await
```

**Comment by jamesbt365** [comment]
This is a 2 part fix, the 1st part was #2887.

**Comment by AlexCzar** [comment]
Can't wait :) I tried applying it myself and specifying git dependency, but some magic happens, and my shuttle app refuses to recognize `serenity::Client` 🤷🏽

**Review by GnomedDev — APPROVED** [review]

**Comment by FichteFoll** [comment]
Hi, I'd just like to mention that a release with this fix would be much appreciated, also considering the number of duplicate issues of #2892 since people keep running into it. For now, I'm staying on 0.10 which still works but there have been some breaking API changes since then, so I presume not everyone would be happy to revert to that.

**Comment by gkuznik** [comment]
@FichteFoll you can use a newer version, this issue was introduced in 0.12.2. `serenity = { version = "=0.12.1" }` in Cargo,.toml also works if you use Poise

**Pull request merged**
