### PR TITLE
Implemented support for multiple activities.

### PR DESCRIPTION
**Pull request by evieluvsrainbows**
If there are any issues with the formatting, I'll try and fix them if needed.

### CODE REVIEW

**Review by Flat — APPROVED** [review]
Looks good. For future PRs maybe don't run the formatter so it's easier to see the intentional changes. Additionally adding tests for de-serialization would be good.

**Comment by Elinvynia** [comment]
@KamranMackey I believe this also closes #673

**Comment by Lakelezz** [comment]
This will need to be based on the `next`-branch, as we no longer accept new features for the v0.8-series!

**Comment by evieluvsrainbows** [comment]
I will rebase this upon the merge of `serenity-await`, in order to not have to rebase it again.

**Pull request closed without merging**
