### PR TITLE
Change builders to use &mut self instead of mut self

### PR DESCRIPTION
**Pull request by PvdBerg1998**
Implements https://github.com/serenity-rs/serenity/issues/329 .

### CODE REVIEW

**Comment by PvdBerg1998** [comment]
Doc examples are currently broken, todo

**Comment by PvdBerg1998** [comment]
@zeyla I sadly no longer have time to work on this and the PR is based on a very old commit, is it still useful? I hope this can be implemented in 0.6

**Comment by zeyla** [comment]
This change is partially already in 0.6 as builders are &mut self, but don't currently return &mut Self. I'll rebase the rest of this in within a few days.

**Comment by PvdBerg1998** [comment]
@zeyla Any update on this? I was cleaning my forks and saw that it has been quite a few days ;)

**Comment by acdenisSK** [comment]
LGTM to merge. However, this pr will need to be retargetted to `v0.6.x` and for [these issues](https://travis-ci.org/serenity-rs/serenity/jobs/393108094#L1032-L1145) to be fixed.

**Comment by acdenisSK** [comment]
As this is outdated and with no response from the author for the past month and some days, this is being closed.

**Pull request closed without merging**
